// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7Z55keo7p9IcYOta8IkoUxh1Mg5NuGg',
    appId: '1:565339751536:web:22365ad115bc3259e8e0b5',
    messagingSenderId: '565339751536',
    projectId: 'loginwithdifferentonlinemedia',
    authDomain: 'loginwithdifferentonlinemedia.firebaseapp.com',
    storageBucket: 'loginwithdifferentonlinemedia.appspot.com',
    measurementId: 'G-N2H9YZQ51Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7vKsh3LisZo1w_OQ2vZ3WvOj-GUEVn2w',
    appId: '1:565339751536:android:a891e0103d5cdfdee8e0b5',
    messagingSenderId: '565339751536',
    projectId: 'loginwithdifferentonlinemedia',
    storageBucket: 'loginwithdifferentonlinemedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSQe479rLlwainaLEeROvGsBYSnKFmd_g',
    appId: '1:565339751536:ios:e7c3ecd19bd4f6cde8e0b5',
    messagingSenderId: '565339751536',
    projectId: 'loginwithdifferentonlinemedia',
    storageBucket: 'loginwithdifferentonlinemedia.appspot.com',
    iosClientId: '565339751536-gro82pp1vdp86qcstne80c8jm0cc7cuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithDifferentOnlineMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSQe479rLlwainaLEeROvGsBYSnKFmd_g',
    appId: '1:565339751536:ios:886c6a730afa90d3e8e0b5',
    messagingSenderId: '565339751536',
    projectId: 'loginwithdifferentonlinemedia',
    storageBucket: 'loginwithdifferentonlinemedia.appspot.com',
    iosClientId: '565339751536-9mdrqb3ea8jhshpq00f10n8i39djith2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithDifferentOnlineMedia.RunnerTests',
  );
}
